### ISSUE TITLE
LGPL license => Apache v2 or BSD?

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/Tasks#8]
Hey,

Would it be possible to switch this library and the relevant dependencies to [Apache v2](https://www.apache.org/licenses/LICENSE-2.0) (preferably) or [BSD 2-clause](https://opensource.org/licenses/BSD-2-Clause)? It seems there are some painful compliance processes for LGPL and some of the text isn't very clear. For example on [my project grl's license](https://github.com/ahundt/grl/blob/master/COPYING.txt) I dual license BSD and Apache v2 at the user's option.

Here is an example of the weird linking compliance/documentation steps:
https://programmers.stackexchange.com/questions/86142/what-exactly-do-i-need-to-do-if-i-use-a-lgpl-licenced-library

additional more detailed discussion:
http://answers.google.com/answers/threadview/id/439136.html

Sorry for the trouble and thanks for your consideration!

**Comment by jorisv** [comment]
Hello,

I will not change the license. But all my repo will be soon transferred to [jrl-umi3218](https://github.com/jrl-umi3218), my hosting lab during my phd. They will maybe change the license (but not for a less permissive one).

I don't really see the issue with LGPL here. The main restriction of the LGPL (that apparently don't appear in the Apache and BSD) is when your software link to some modified version of Tasks, you have to allow access to this modified version of Tasks to people you're distributing your software.

Since your project is under both BSD and Apache v2 license you have nothing else to do since the user will be able to rebuild your software with the specific version of Tasks he want.

Hope I have helped.

**Comment by ahundt** [comment]
I'm trying to keep my own project available to commercial projects with as low a bar as possible. Even though I'm licensed BSD the dependencies must meet that linking requirement as well even if they only use my library which in turn uses yours. Don't worry, I understand if your motivations preclude that!
