### ISSUE TITLE
is this or jrl-umi3218 the ongoing location for tasks library?

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/Tasks#9]
I noticed that some development has moved to:

https://github.com/jrl-umi3218/Tasks

although some items are missing there such as:
https://github.com/jorisv/Eigen3ToPython
is not in:
https://github.com/jrl-umi3218/Eigen3ToPython

Just wanted to clarify so I use the right ones!

**Comment by haudren** [comment]
Hello,

Yes, the project has been moved under the jrl-umi3218 to facilitate development with other members of the lab. Indeed, Eigen3ToPython was not moved, because we have developed new python bindings. Unfortunately, they are closely linked to proprietary code, and cannot be released for the time being.

So, to use the newest versions, use the jrl-umi3218 ones when they exist!

**Comment by ahundt** [comment]
@haudren Thanks! Would it then be possible to enable github issues on the various repositories there? Then questions like this could be on the repository where development actually happens.

Regarding the bindings:
- Will the old bindings continue to work or should I assume they could stop working at any time? 
- Do the new bindings run faster or something & will it eventually be possible to release them?

Thanks!

**Comment by ahundt** [comment]
Also it looks like http://github.com/jorisv/sva_rbdyn_tutorials has also not been migrated.

**Comment by haudren** [comment]
Ok, I'll see with the group administrator to enable the issues, I'm pretty sure this is a mistake.
- The old bindings are no longer actively maintained: I try to make them build whenever I make changes, but this is not a guarantee. However, as there are few changes to sva/RBDyn nowadays, they should be relatively stable.
- The new bindings are faster, and I can see if we can release them, but this will take time...
- Similarly, the `sva_rbdyn_tutorials` have not been migrated because they mainly depend on the older bindings. I updated them to work with our new bindings there: https://github.com/haudren/sva_rbdyn_tutorials but I don't have a version that works with the up-to-date old bindings.

**Comment by gergondet** [comment]
Hi,

I've enabled issues on all the repositories that were migrated to the jrl-umi3218 group so you can open new discussions there if you wish.

**Comment by ahundt** [comment]
Great! that fixes a few of the issues. One other is that search isn't enabled on the jrl-umi3218 organization version. This can be achieved with the help of @jorisv through a [github repository transfer](https://help.github.com/articles/about-repository-transfers/).

**Comment by gergondet** [comment]
We migrated officially all relevant repositories from @jorisv to the jrl-umi3218 group. 

@fkanehiro @eiichi @kheddar it seems you were following the jrl-umi3218 fork of [jrl-umi3218/SpaceVecAlg](https://github.com/jrl-umi3218/SpaceVecAlg), [jrl-umi3218/RBDyn](https://github.com/jrl-umi3218/RBDyn), [jrl-umi3218/eigen-qld](https://github.com/jrl-umi3218/eigen-qld) and [jrl-umi3218/Tasks](https://github.com/jrl-umi3218/Tasks) you will have to follow them again followig the move
